app/__init__.py
# app/__init__.py

from flask import Flask

def create_app():
    app = Flask(__name__)

    # Load configuration settings from config.py
    app.config.from_object('config')

    # Register blueprints for different parts of the app
    from .routes import main_bp, image_gen_bp, essay_gen_bp, ai_chatbot_bp, speech_to_text_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(image_gen_bp, url_prefix='/image-generator')
    app.register_blueprint(essay_gen_bp, url_prefix='/essay-generator')
    app.register_blueprint(ai_chatbot_bp, url_prefix='/ai-chatbot')
    app.register_blueprint(speech_to_text_bp, url_prefix='/speech-to-text')

    return app

app/routes.py
import os
import uuid
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from openai.error import InvalidRequestError
from .utils import (
    generate_image,
    generate_essay,
    generate_ai_chatbot_response,
    generate_corrected_transcript_with_cloudinary_audio_file,
    generate_corrected_transcript_with_local_audio_file,
)
import cloudinary.uploader
import cloudinary.api
from dotenv import load_dotenv

# Load environment variables from .flaskenv
load_dotenv()

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
)

main_bp = Blueprint("main", __name__)
image_gen_bp = Blueprint("image_gen", __name__)
essay_gen_bp = Blueprint("essay_gen", __name__)
ai_chatbot_bp = Blueprint("ai_chatbot", __name__)
speech_to_text_bp = Blueprint("speech_to_text", __name__)


@main_bp.route("/", methods=("GET", "POST"))
def index():
    return redirect(url_for("ai_chatbot.ai_chatbot"))


@image_gen_bp.route("/", methods=("GET", "POST"))
def image_generator():
    if request.method == "POST":
        prompt = request.form["description"]
        status, result = generate_image(prompt)
        return redirect(
            url_for(
                "image_gen.image_generator",
                status=status,
                result=result,
                prompt=prompt,
            )
        )
    args = request.args
    status, result, prompt = args.get("status"), args.get("result"), args.get("prompt")
    return render_template(
        "image_generator.html", status=status, result=result, prompt=prompt
    )


@essay_gen_bp.route("/", methods=("GET", "POST"))
def essay_generator():
    if request.method == "POST":
        essay_idea = request.form.get("essayIdea", "")
        # Get the value of "essayWordCount" from the form or provide a default value (e.g., 500) if not present
        essay_word_count = request.form.get("essayWordCount", 500)
        prompt = f"Write me an essay about {essay_idea} with {essay_word_count} words."
        messages = [{"role": "user", "content": prompt}]
        status, result = generate_essay(messages)
        return jsonify({"status": status, "result": result, "prompt": prompt}), 200
    return render_template("essay_generator.html")


@ai_chatbot_bp.route("/", methods=("GET", "POST"))
def ai_chatbot():
    messages = (
        request.args.get("messages")
        if request.args.get("messages")
        else [{"role": "system", "content": "What can I help you today?"}]
    )
    if request.method == "POST":
        prompt = request.form["input"]
        messages.append({"role": "user", "content": prompt})
        status, messages = generate_ai_chatbot_response(messages)
        return jsonify({"status": status, "messages": messages}), 200
    return render_template("ai_chatbot.html", messages=messages)


# save audio file to Cloudinary
@speech_to_text_bp.route("/", methods=("GET", "POST"))
def speech_to_text():
    if request.method == "POST":
        if "audio" in request.files:
            audio_file = request.files["audio"]
            if audio_file:
                # Generate a unique filename for the audio file
                folder = "open-ai-audio"
                filename = f"{str(uuid.uuid4())}.wav"
                # Save the audio file to the "open-ai-audio" folder in Cloudinary
                result = cloudinary.uploader.upload(
                    audio_file,
                    folder=folder,
                    resource_type="raw",
                    public_id=filename,
                    overwrite=True,
                )
                # Get the public URL of the uploaded audio file
                audio_url = result["secure_url"]
                (
                    status,
                    result,
                ) = generate_corrected_transcript_with_cloudinary_audio_file(audio_url)
                # Delete the file
                public_id = f"{folder}/{filename}"
                cloudinary.uploader.destroy(public_id, resource_type="raw")
                return jsonify({"status": status, "result": result}), 200
        return jsonify({"status": "error", "message": "No audio file received."})
    return render_template("speech_to_text.html")


# save audio file to Local File Sytem
# @speech_to_text_bp.route("/", methods=("GET", "POST"))
# def speech_to_text():
#     if request.method == "POST":
#         if "audio" in request.files:
#             audio_file = request.files["audio"]
#             if audio_file:
#                 # Generate a unique filename for the audio file
#                 filename = f"{str(uuid.uuid4())}.wav"
#                 # Save the audio file to the "static/audio" directory
#                 audio_file_path = os.path.join("app", "static", "audio", filename)
#                 audio_file.save(audio_file_path)
#                 # Check if the file exists before generating the transcript
#                 if os.path.isfile(audio_file_path):
#                     status, result = generate_corrected_transcript_with_local_audio_file(audio_file_path)
#                     # Close the file
#                     audio_file.close()
#                     # Delete the file
#                     os.remove(audio_file_path)
#                     return jsonify(status=status, result=result)
#         return jsonify({"status": "error", "message": "No audio file received."})
#     return render_template("speech_to_text.html")

app/templates/ai_chatbot.html
{% extends 'index.html' %} {% block content %}

<div class="container-fluid vh-100">
  <div class="card h-75">
    <div class="card-body overflow-auto">
      <div id="chatbox">
        <div class="d-flex flex-row bg-light py-4">
          <span class="material-symbols-rounded mx-3"> smart_toy </span>
          <span> Hi! What can I help you today?</span>
        </div>
      </div>
      <div id="loading">
        <div class="d-flex flex-row bg-light py-4 d-none">
          <span class="material-symbols-rounded mx-3"> smart_toy </span>
          <span class="spinner-border spinner-border-sm" role="status"> </span>
        </div>
      </div>
      <div id="response-failed">
        <div class="d-flex flex-row bg-light py-4 text-danger d-none">
          <span class="material-symbols-rounded mx-3"> smart_toy </span>
          <span> Something went wrong. Please reload and try again.</span>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="input-group">
        <button
          class="btn btn-primary d-flex justify-content-center"
          type="button"
          id="recordBtn"
        >
          <span class="material-symbols-rounded"> mic </span>
        </button>
        <button
          class="btn btn-danger d-flex justify-content-center d-none rounded-start"
          id="stopBtn"
        >
          <span class="material-symbols-rounded"> stop_circle </span>
        </button>
        <button
          class="btn btn-dark rounded-start disabled d-none"
          id="loadingBtn"
        >
          <span class="spinner-border spinner-border-sm" role="status"> </span>
        </button>
        <input
          type="text"
          class="form-control"
          id="userInput"
          placeholder="Speak or type your text here..."
        />

        <button class="btn btn-primary" type="button" id="sendUserInputBtn">
          Send
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/essay_generator.html
{% extends 'index.html' %} {% block content %}
<div
  class="alert alert-danger d-flex flex-row d-none"
  role="alert"
  id="responseFailedMsg"
>
  <span class="material-symbols-rounded me-2"> warning </span>
  <span> Something went wrong. Please reload and try again.</span>
</div>

<div
  class="alert alert-success alert-dismissible fade show d-flex flex-row d-none"
  role="alert"
  id="essayCopiedMsg"
>
  <span class="material-symbols-rounded me-2"> check_circle </span>
  <span> Essay is copied!</span>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>

<form action="" method="">
  <div class="form-group mb-3">
    <label class="form-label">Write me an essay about: </label>
    <input
      type="text"
      class="form-control"
      id="essayIdea"
      name="essayIdea"
      requried
    />
  </div>
  <div class="form-group mb-3">
    <div class="row">
      <label for="essayWordCount" class="col-sm-2 col-form-label"
        >Word count:</label
      >
      <div class="col-auto">
        <input
          type="number"
          class="form-control"
          id="essayWordCount"
          name="essayWordCount"
          max="3000"
          min="100"
        />
      </div>
      <div class="col-auto ms-auto">
        <button
          type="button"
          class="btn btn-primary mb-3"
          id="generateEssayBtn"
        >
          Generate
        </button>
        <button type="reset" class="btn btn-secondary mb-3">Clear</button>
      </div>
    </div>
  </div>
</form>

<div class="card flex-fill mt-5">
  <div class="card-body">
    <h5 class="card-title">
      Result
      <span
        class="spinner-border spinner-border-sm d-none"
        id="loadingEssayResult"
        role="status"
      >
      </span>
    </h5>
    <textarea class="form-control" id="essayResult" rows="20"></textarea>

    <div class="mt-3 float-end">
      <button type="submit" class="btn btn-primary" id="copyEssayBtn">
        Copy
      </button>
    </div>
  </div>
</div>
{% endblock %}

app/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item mx-3">
        <a class="nav-link" href="{{ url_for('ai_chatbot.ai_chatbot') }}"
          >AI ChatBot</a
        >
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{{ url_for('image_gen.image_generator') }}"
          >Image Generator</a
        >
      </li>
      <li class="nav-item mx-3">
        <a
          class="nav-link"
          href="{{ url_for('essay_gen.essay_generator') }}"
          >Essay Generator</a
        >
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{{ url_for('speech_to_text.speech_to_text') }}"
          >Speech To Text</a
        >
      </li>
    </ul>
  </div>s
</nav>

app/templates/image_generator.html
{% extends 'index.html' %} {% block content %}

<form action="{{ url_for('image_gen.image_generator') }}" method="post">
  <div class="mb-3">
    <label class="form-label">Turning your idea into an image</label>
    <textarea
      class="form-control"
      name="description"
      rows="2"
      required
      placeholder="e.g. abstract pencil and watercolor art of a lonely robot holding a balloon"
    ></textarea>
    <div class="text-end mt-3">
      <button type="submit" class="btn btn-primary">Generate</button>
    </div>
  </div>
</form>

<div class="text-center">
  {% if status == "success" %}
  <p class="fs-5 fw-bolder">Image Result</p>
  <p>{{ prompt }}</p>
  <img
    src="{{ result
       }}"
    class="img-fluid img-thumbnail p-3"
  />
  {% elif status == "fail" %}
  <div class="alert alert-danger" role="alert">
    Something went wrong. Please reload and try again.
  </div>
  {% endif %}
</div>

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Practice with Open AI Platform</title>
    <link rel=icon href="{{ url_for('static', filename='image/favicon.png') }}" sizes="16x16" type="image/png">

    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- Google Icon -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
  </head>
  <body class="bg-light">
    {% include 'header.html' %}

    <div class="container p-5">{% block content %} {% endblock %}</div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap Javascripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <!--   <script src="{{ url_for('static', filename='js/script.js') }}"></script> -->
    <script src="{{ url_for('static', filename='js/essay_generator.js') }}"></script>
    <script src="{{ url_for('static', filename='js/ai_chatbot.js') }}"></script>
    <script src="{{ url_for('static', filename='js/speech_to_text.js') }}"></script>
  </body>
</html>

app/templates/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>

app/templates/speech_to_text.html
{% extends 'index.html' %} {% block content %}
<div class="container py-2">
  <div class="card flex-fill">
    <div class="card-body">
      <h5 class="card-title">User Voice Input</h5>
      <textarea class="form-control mb-3" id="userInput" rows="10"></textarea>
      <div class="d-flex justify-content-end">
        <button
          class="btn btn-outline-primary d-flex justify-content-center"
          id="recordBtn"
        >
          <span class="material-symbols-rounded"> mic </span>
        </button>
        <button
          class="btn btn-outline-danger d-flex justify-content-center d-none"
          id="stopBtn"
        >
          <span class="material-symbols-rounded"> stop_circle </span>
        </button>
        <button class="btn btn-outline-dark disabled d-none" id="loadingBtn">
          <span class="spinner-border spinner-border-sm" role="status"> </span>
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item mx-3">
          <a class="nav-link" href="{{ url_for('image_generator') }}"
            >Image Generator</a
          >
        </li>
        <li class="nav-item mx-3">
          <a class="nav-link" href="#">Content Title Generator</a>
        </li>
        <li class="nav-item mx-3">
          <a class="nav-link" href="#">Persona ChatGPT</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/image_generator.html
{% extends 'index.html' %} {% block content %}

<form action="/image-generator" method="post">
  <div class="mb-3">
    <label class="form-label">Turning your idea into an image</label>
    <textarea
      class="form-control"
      name="description"
      rows="2"
      required
      placeholder="e.g. broccoli with sunglasses"
    ></textarea>
    <div class="text-end mt-3">
      <button type="submit" class="btn btn-primary">Generate</button>
    </div>
  </div>
</form>

{% if result %}
<div class="text-center">
  <p class="fs-5 fw-bolder">Image Result</p>
  <p>{{ prompt }}</p>
  <img
    src="{{ result
       }}"
    class="img-fluid img-thumbnail p-3"
  />
  <div>{% endif %} {% endblock %}</div>
</div>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My First Bootstrap Page</title>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
  </head>
  <body class="bg-light">
    {% include 'header.html' %}

    <div class="container p-5">{% block content %} {% endblock %}</div>

    <!-- Bootstrap Javascripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>